// Base de ICMS interestadual com origem fixa em SP, extraida da planilha de referencia.
export const icmsPorEstado = [
  { sigla: 'AC', aliquota: 0.07 },
  { sigla: 'AL', aliquota: 0.07 },
  { sigla: 'AM', aliquota: 0.07 },
  { sigla: 'AP', aliquota: 0.07 },
  { sigla: 'BA', aliquota: 0.07 },
  { sigla: 'CE', aliquota: 0.07 },
  { sigla: 'DF', aliquota: 0.07 },
  { sigla: 'ES', aliquota: 0.07 },
  { sigla: 'GO', aliquota: 0.07 },
  { sigla: 'MA', aliquota: 0.07 },
  { sigla: 'MT', aliquota: 0.07 },
  { sigla: 'MS', aliquota: 0.07 },
  { sigla: 'MG', aliquota: 0.12 },
  { sigla: 'PA', aliquota: 0.07 },
  { sigla: 'PB', aliquota: 0.07 },
  { sigla: 'PR', aliquota: 0.12 },
  { sigla: 'PE', aliquota: 0.07 },
  { sigla: 'PI', aliquota: 0.07 },
  { sigla: 'RN', aliquota: 0.07 },
  { sigla: 'RS', aliquota: 0.12 },
  { sigla: 'RJ', aliquota: 0.12 },
  { sigla: 'RO', aliquota: 0.07 },
  { sigla: 'RR', aliquota: 0.07 },
  { sigla: 'SC', aliquota: 0.12 },
  { sigla: 'SP', aliquota: 0.18 },
  { sigla: 'SE', aliquota: 0.07 },
  { sigla: 'TO', aliquota: 0.07 },
  {
    sigla: 'IM',
    aliquota: 0.04,
    badge: 'Importados',
    tooltip: 'Aliquota interestadual para produtos importados conforme a Resolucao SF 13/2012.'
  }
];
