name: CI - Grupo 13 MarkUp

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      app: ${{ steps.changes.outputs.app }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'
            app:
              - 'app/**'

  unitTestApi:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências da API
        working-directory: api
        run: npm ci

      - name: Rodar testes unitários
        working-directory: api
        run: npm test

  buildApp:
    needs: detect-changes
    if: needs.detect-changes.outputs.app == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências do App
        working-directory: app
        run: npm ci

      - name: Build do App
        working-directory: app
        run: npm run build
