name: Teste and Deploy

on:
  push:
    branches: [main, dev]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.changes.outputs.api }}
      web: ${{ steps.changes.outputs.web }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            api:
              - 'api/**'
            web:
              - 'web/**'
              
  unitTestApi:
    needs: detect-changes
    if: needs.detect-changes.outputs.api == 'true'
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Get Code from repository
        uses: actions/checkout@v4
      
      - name: verifica se fez corretamente
        run: ls -la
        
      - name: Instala o Node na maquina virtual        
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Instala as dependencias do projeto
        working-directory: api 
        run: npm ci
        
      - name: Roda os testes
        working-directory: api 
        run: npm run test 
        
      - name: verifica se fez corretamente
        working-directory: api 
        run: ls -la        

  deployVercel:
    needs: [detect-changes, unitTestApi]
    # Executa se houver alterações na web ou na api, contanto que os testes da api não tenham falhado
    if: |
      always() && 
      !contains(needs.unitTestApi.result, 'failure') && 
      !contains(needs.unitTestApi.result, 'cancelled') && 
      (needs.detect-changes.outputs.web == 'true' || needs.detect-changes.outputs.api == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Get Code from repository
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
          working-directory: ./web
